export const
    SET_LANG = 'SET_LANG',
    SET_COOKIES_AGREEMENT = 'SET_COOKIES_AGREEMENT',
    SET_PRODUCTS = 'SET_PRODUCTS',
    SET_FILTERS = 'SET_FILTERS',
    SET_CATEGORIES = 'SET_CATEGORIES';
